sudo: required
services:
  - docker

script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=mnbbrown/ci-web
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export TAG="latest";
    else
      export TAG=$TRAVIS_BRANCH ;
    fi
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker push $REPO
